// Code generated by MockGen. DO NOT EDIT.
// Source: contracts/cache.go
//
// Generated by this command:
//
//	mockgen -source=contracts/cache.go -destination=contracts/mocks/mock_cache.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	product "orderflow/domains/product"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProductCache is a mock of ProductCache interface.
type MockProductCache struct {
	ctrl     *gomock.Controller
	recorder *MockProductCacheMockRecorder
	isgomock struct{}
}

// MockProductCacheMockRecorder is the mock recorder for MockProductCache.
type MockProductCacheMockRecorder struct {
	mock *MockProductCache
}

// NewMockProductCache creates a new mock instance.
func NewMockProductCache(ctrl *gomock.Controller) *MockProductCache {
	mock := &MockProductCache{ctrl: ctrl}
	mock.recorder = &MockProductCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductCache) EXPECT() *MockProductCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockProductCache) Get(ctx context.Context, id string) (*product.Product, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*product.Product)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProductCacheMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProductCache)(nil).Get), ctx, id)
}

// Set mocks base method.
func (m *MockProductCache) Set(ctx context.Context, p *product.Product) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Set", ctx, p)
}

// Set indicates an expected call of Set.
func (mr *MockProductCacheMockRecorder) Set(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockProductCache)(nil).Set), ctx, p)
}
